#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>
#include <limits>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::fixed;
using std::string;
using std::copy;
using std::swap;
using std::vector;
using std::min;
using std::stoi;